version: '3.1'

services:
# EXPRESS API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    envirionment:
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/backend
    restart: unless-stopped
# REACT APP
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      ports:
        - "3000:3000"
      volumes:
        - ./frontend:/frontend
      restart: unless-stopped
# REVERSE PROXY / ROUTING
  caddy:
    image: caddy/2.7.6-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./Caddyfile.dev:/etc/caddy/Caddyfile"
      - "/etc/caddy/data:/data"
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
