version: '3.1'

services:
# SERVICES
  backend:
    image: node:hydrogen-slim
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    volumes:
      - ./backend:/backend

  frontend:
      image: node:hydrogen-slim
      ports:
        - "${FRONTEND_PORT}:${FRONT_END}"
      volumes:
        - ./frontend:/frontend

  caddy:
    image: caddy/caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./caddy:/etc/caddy"
    depends_on:
      - backend
      - frontend
