version: '3.1'

services:
# EXPRESS API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
    restart: unless-stopped
    command: node ./build/index.js
# REACT APP
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    restart: unless-stopped
    command: pm2-runtime serve ./build 3000 --name frontend
# REVERSE PROXY / ROUTING
  caddy:
    image: caddy:2.7.6-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
      - "/etc/caddy/data:/data"
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
