version: '3'

services:
# EXPRESS API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
    restart: unless-stopped
    # command: node /build/index.js
    networks:
      - web-server
    entrypoint: ["node", "/app/backend/build/index.js"]
# App and caddy
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      # - "3000:3000"
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/app/frontend
      - "./Caddyfile:/etc/caddy/Caddyfile"
      - "/etc/caddy/data:/data"
    restart: unless-stopped
    networks:
      - web-server
    #command: pm2-runtime serve ./build 3000 --name frontend
# REVERSE PROXY / ROUTING
  # caddy:
  #   image: caddy:2.7.6-alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - "./Caddyfile:/etc/caddy/Caddyfile"
  #     - "/etc/caddy/data:/data"
  #   depends_on:
  #     - backend
  #     - frontend
  #   restart: unless-stopped
networks:
  web-server:
    driver: bridge